-- USER SQL
DROP USER tw_admin;

CREATE USER tw_admin IDENTIFIED BY parola 
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER tw_admin QUOTA 2000M ON USERS;

-- ROLES
GRANT "CONNECT" TO tw_admin ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO tw_admin ;
GRANT CREATE VIEW TO tw_admin ;
GRANT CREATE TABLE TO tw_admin ;
GRANT CREATE SYNONYM TO tw_admin ;
GRANT CREATE SEQUENCE TO tw_admin ;
GRANT CREATE PROCEDURE TO tw_admin ;
