CREATE INDEX DATE_IND ON SOLVEDTASKS(TO_DATE(TO_CHAR(completedDate,'DD-MM-YYYY'),'DD-MM-YYYY'));
/
CREATE INDEX ST_P_ID_IND ON SOLVEDTASKS(P_ID);
/
CREATE INDEX ST_TASK_ID_IND ON SOLVEDTASKS(TASK_ID);
/
CREATE INDEX ST_HASSOLUTION_IND ON SOLVEDTASKS(HASSOLUTION);
/

CREATE INDEX TASK_NAME ON TASKS(TASK_NAME);
/

CREATE INDEX P_TA_IND ON PERSONS(TASK_ATTEMPTED_COUNTER);
/
CREATE INDEX P_TC_IND ON PERSONS(TASK_COMPLETED_COUNTER);
/